version: '3'

networks:
  default:
    name: app-net 
    external: true

services:

  {projectName}:
    image: {projectName}:local
    container_name: {projectName}
    restart: unless-stopped
    ports:
      - {port}:3000
    